console.log("Number Guess Game");

const btn = document.querySelector(".btn");
btn.addEventListener("click", guessNumber);

// program where the user has to guess a number generated by a program

function guessNumber() {
    // generating a random integer from 1 to 100
    const random = Math.floor(Math.random() * 100) + 1;

    // take input from the user
    let number2 = document.getElementById("guess");
    let number = number2.value;

    // check if the guess is incorrect
    // if(number !== random) {
    //     console.log('You guessed the Incorrect number.');
    //     hint.innerHTML = "You guessed the Incorrect number";
    // }

     if(number == random) {
        // console.log('You guessed the correct number.');
        hint.innerHTML = "You guessed the correct number";
    }
    else if(number > random) {
        // console.log('You guessed the correct number. high');
        hint.innerHTML = "Your selected number is too high";
    }
    else if(number < random) {
        // console.log('You guessed the correct number.low');
        hint.innerHTML = "Your selected number is too Low";
    }
}

// call the function
guessNumber();
hint.innerHTML = "";

